init

diff --git a/bin/hive b/bin/hive
--- a/bin/hive
+++ b/bin/hive
@@ -25,11 +25,12 @@ bin=`cd "$bin"; pwd`
 
 . "$bin"/hive-config.sh
 
+TMP_USER_DIR="/tmp/${USER}"
+STDERR="${TMP_USER_DIR}/stderr"
 SERVICE=""
 HELP=""
 SKIP_HBASECP=false
 SKIP_HADOOPVERSION=false
-EXECUTE_WITH_JAVA=false
 
 SERVICE_ARGS=()
 while [ $# -gt 0 ]; do
@@ -86,17 +87,6 @@ if [ "$SERVICE" = "" ] ; then
   fi
 fi
 
-USE_BEELINE_FOR_HIVE_CLI="true"
-if [[ "$SERVICE" == "cli" && "$USE_BEELINE_FOR_HIVE_CLI" == "true" ]] ; then
-  CLIUSER=`whoami`
-  SERVICE="beeline"
-fi
-
-if [[ "$SERVICE" == "beeline" && ! -z "$BEELINE_URL_LEGACY" ]] ; then
-  SERVICE="beeline"
-  SERVICE_ARGS=("${SERVICE_ARGS[@]}" "-c" "${BEELINE_URL_LEGACY}")
-fi
-
 if [[ "$SERVICE" =~ ^(help|version|orcfiledump|rcfilecat|schemaTool|cleardanglingscratchdir|metastore|beeline|llapstatus|llap)$ ]] ; then
   SKIP_HBASECP=true
 fi
@@ -109,42 +99,38 @@ if [ -f "${HIVE_CONF_DIR}/hive-env.sh" ]; then
   . "${HIVE_CONF_DIR}/hive-env.sh"
 fi
 
-if [ "$SERVICE" != "beeline" ]; then
-  if [[ -z "$SPARK_HOME" ]]
-  then
-    bin=`dirname "$0"`
-    # many hadoop installs are in dir/{spark,hive,hadoop,..}
-    if test -e $bin/../../spark; then 
-      sparkHome=$(readlink -f $bin/../../spark)
-      if [[ -d $sparkHome ]]
-      then
-        export SPARK_HOME=$sparkHome
-      fi
+if [[ -z "$SPARK_HOME" ]]
+then
+  bin=`dirname "$0"`
+  # many hadoop installs are in dir/{spark,hive,hadoop,..}
+  if test -e $bin/../../spark; then 
+    sparkHome=$(readlink -f $bin/../../spark)
+    if [[ -d $sparkHome ]]
+    then
+      export SPARK_HOME=$sparkHome
     fi
   fi
 fi
 
-CLASSPATH="${TEZ_CONF_DIR:-/etc/tez/conf}:${HIVE_CONF_DIR}"
+CLASSPATH="${HIVE_CONF_DIR}"
 
 HIVE_LIB=${HIVE_HOME}/lib
 
-if [ "$SERVICE" != "beeline" ]; then
-  # needed for execution
-  if [ ! -f ${HIVE_LIB}/hive-exec-*.jar ]; then
-    echo "Missing Hive Execution Jar: ${HIVE_LIB}/hive-exec-*.jar"
-    exit 1;
-  fi
+# needed for execution
+if [ ! -f ${HIVE_LIB}/hive-exec-*.jar ]; then
+  echo "Missing Hive Execution Jar: ${HIVE_LIB}/hive-exec-*.jar"
+  exit 1;
+fi
 
-  if [ ! -f ${HIVE_LIB}/hive-metastore-*.jar ]; then
-    echo "Missing Hive MetaStore Jar"
-    exit 2;
-  fi
+if [ ! -f ${HIVE_LIB}/hive-metastore-*.jar ]; then
+  echo "Missing Hive MetaStore Jar"
+  exit 2;
+fi
 
-  # cli specific code
-  if [ ! -f ${HIVE_LIB}/hive-cli-*.jar ]; then
-    echo "Missing Hive CLI Jar"
-    exit 3;
-  fi
+# cli specific code
+if [ ! -f ${HIVE_LIB}/hive-cli-*.jar ]; then
+  echo "Missing Hive CLI Jar"
+  exit 3;
 fi
 
 for f in ${HIVE_LIB}/*.jar; do
@@ -226,69 +212,61 @@ fi
 # HADOOP_HOME env variable overrides hadoop in the path
 HADOOP_HOME=${HADOOP_HOME:-${HADOOP_PREFIX:-$HADOOP_DIR}}
 if [ "$HADOOP_HOME" == "" ]; then
-  if [ "$SERVICE" != "beeline" ]; then
-    echo "Cannot find hadoop installation: \$HADOOP_HOME or \$HADOOP_PREFIX must be set or hadoop must be in the path";
-    exit 4;
-  fi
-else
-  # add distcp to classpath, hive depends on it
-  for f in ${HADOOP_HOME}/share/hadoop/tools/lib/hadoop-distcp-*.jar; do
-    export HADOOP_CLASSPATH=${HADOOP_CLASSPATH}:$f;
-  done
+  echo "Cannot find hadoop installation: \$HADOOP_HOME or \$HADOOP_PREFIX must be set or hadoop must be in the path";
+  exit 4;
 fi
+
+# add distcp to classpath, hive depends on it
+for f in ${HADOOP_HOME}/share/hadoop/tools/lib/hadoop-distcp-*.jar; do
+  export HADOOP_CLASSPATH=${HADOOP_CLASSPATH}:$f;
+done
 
 HADOOP=$HADOOP_HOME/bin/hadoop
 if [ ! -f ${HADOOP} ]; then
-  if [ "$SERVICE" != "beeline" ]; then
-    echo "Cannot find hadoop installation: \$HADOOP_HOME or \$HADOOP_PREFIX must be set or hadoop must be in the path";
-    exit 4;
-  else
-    JAVAEXE=$JAVA_HOME/bin/java
-    if [ ! -f ${JAVAEXE} ]; then
-      JAVAEXE=`which java 2>/dev/null`
-      if [ ! -f ${JAVAEXE} ]; then
-        echo "Cannot find hadoop or java installation: \$HADOOP_HOME or \$JAVA_HOME must be set or PATH be set";
-        exit 5;
-      fi
-    else
-      echo "HADOOP_HOME not set, executing beeline using JAVA";
-      export EXECUTE_WITH_JAVA=true
-      if [ -z ${HIVE_LIB} ]; then
-        export HIVE_LIB="${PWD}/lib"
-        export JAVAEXE=$JAVAEXE
-      fi
-    fi
+  echo "Cannot find hadoop installation: \$HADOOP_HOME or \$HADOOP_PREFIX must be set or hadoop must be in the path";
+  exit 4;
+fi
+
+if [ ! -d ${TMP_USER_DIR} ]; then
+  mkdir -p ${TMP_USER_DIR} 2> /dev/null
+  if [ $? -ne 0 ]; then
+    STDERR="/dev/tty"
   fi
 fi
 
-if [ "$EXECUTE_WITH_JAVA" == "false" ]; then
-  if [ "$SKIP_HADOOPVERSION" = false ]; then
-    # Make sure we're using a compatible version of Hadoop
-    if [ "x$HADOOP_VERSION" == "x" ]; then
-        HADOOP_VERSION=$($HADOOP version 2>&2 | awk -F"\t" '/Hadoop/ {print $0}' | cut -d' ' -f 2);
-    fi
+if [ "${STDERR}" != "/dev/null" ] && [ ! -f ${STDERR} ]; then
+  touch ${STDERR} 2> /dev/null
+  if [ $? -ne 0 ]; then
+    STDERR="/dev/tty"
+  fi
+fi
+
+if [ "$SKIP_HADOOPVERSION" = false ]; then
+  # Make sure we're using a compatible version of Hadoop
+  if [ "x$HADOOP_VERSION" == "x" ]; then
+      HADOOP_VERSION=$($HADOOP version 2>> ${STDERR} | awk -F"\t" '/Hadoop/ {print $0}' | cut -d' ' -f 2);
+  fi
   
-    # Save the regex to a var to workaround quoting incompatabilities
-    # between Bash 3.1 and 3.2
-    hadoop_version_re="^([[:digit:]]+)\.([[:digit:]]+)(\.([[:digit:]]+))?.*$"
+  # Save the regex to a var to workaround quoting incompatabilities
+  # between Bash 3.1 and 3.2
+  hadoop_version_re="^([[:digit:]]+)\.([[:digit:]]+)(\.([[:digit:]]+))?.*$"
   
-    if [[ "$HADOOP_VERSION" =~ $hadoop_version_re ]]; then
+  if [[ "$HADOOP_VERSION" =~ $hadoop_version_re ]]; then
       hadoop_major_ver=${BASH_REMATCH[1]}
       hadoop_minor_ver=${BASH_REMATCH[2]}
       hadoop_patch_ver=${BASH_REMATCH[4]}
-    else
+  else
       echo "Unable to determine Hadoop version information."
       echo "'hadoop version' returned:"
       echo `$HADOOP version`
       exit 5
-    fi
+  fi
   
-    if [ "$hadoop_major_ver" -lt "1" -a  "$hadoop_minor_ver$hadoop_patch_ver" -lt "201" ]; then
+  if [ "$hadoop_major_ver" -lt "1" -a  "$hadoop_minor_ver$hadoop_patch_ver" -lt "201" ]; then
       echo "Hive requires Hadoop 0.20.x (x >= 1)."
       echo "'hadoop version' returned:"
       echo `$HADOOP version`
       exit 6
-    fi
   fi
 fi
 
@@ -317,7 +295,7 @@ if [ "$SKIP_HBASECP" = false ]; then
   if [[ -n $HBASE_BIN ]] ; then
     # exclude ZK, PB, and Guava (See HIVE-2055)
     # depends on HBASE-8438 (hbase-0.94.14+, hbase-0.96.1+) for `hbase mapredcp` command
-    for x in $($HBASE_BIN mapredcp 2>&2 | tr ':' '\n') ; do
+    for x in $($HBASE_BIN mapredcp 2>> ${STDERR} | tr ':' '\n') ; do
       if [[ $x == *zookeeper* || $x == *protobuf-java* || $x == *guava* ]] ; then
         continue
       fi
@@ -373,12 +351,10 @@ fi
 
 if [[ "$SERVICE" =~ ^(hiveserver2|beeline|cli)$ ]] ; then
   # If process is backgrounded, don't change terminal settings
-  if [[ ( ! $(ps -o stat= -p $$) =~ "+" ) && ! ( -p /dev/stdin ) && ( ! $(ps -o tty= -p $$) =~ "?" ) ]]; then
+  if [[ ( ! $(ps -o stat= -p $$) =~ "+" ) && ! ( -p /dev/stdin ) ]]; then
     export HADOOP_CLIENT_OPTS="$HADOOP_CLIENT_OPTS -Djline.terminal=jline.UnsupportedTerminal"
   fi
 fi
-
-export JVM_PID="$$"
 
 if [ "$TORUN" = "" ] ; then
   echo "Service $SERVICE not found"
